### ISSUE TITLE
StaticJsonBuffer is a class from ArduinoJson 5

### ISSUE THREAD

**Issue by dbaccello** [baptistecdr/PS4-OpenESPHost#1]
`> Executing task: platformio run <

Processing esp12e (platform: espressif8266; board: esp12e; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp12e.html
PLATFORM: Espressif 8266 2.3.2 > Espressif ESP8266 ESP-12E
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: toolchain-xtensa 2.40802.191122 (4.8.2), framework-arduinoespressif8266 2.20603.191216 (2.6.3), tool-esptool 1.413.0 (4.13), tool-esptoolpy 1.20800.0 (2.8.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 32 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ArduinoJson> 6.13.0
|-- <ESP Async WebServer> 1.2.3
|   |-- <ESPAsyncTCP> 1.2.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson> 6.13.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESPAsyncTCP> 1.2.2
|   |-- <ESP8266WiFi> 1.0
Building in release mode
Compiling .pio/build/esp12e/src/main.cpp.o
src/main.cpp:35:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6
     StaticJsonBuffer<384> jsonBuffer;
           ^
src/main.cpp:68:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6
     StaticJsonBuffer<384> jsonBuffer;
           ^
src/main.cpp:125:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6
         DynamicJsonBuffer jsonBuffer;
           ^
src/main.cpp: In function 'void loadConfiguration(const char*, Configuration&)':
src/main.cpp:35:21: error: expected primary-expression before '<' token
     StaticJsonBuffer<384> jsonBuffer;
                     ^
src/main.cpp:35:27: error: 'jsonBuffer' was not declared in this scope
     StaticJsonBuffer<384> jsonBuffer;
                           ^
src/main.cpp:38:15: error: 'ArduinoJson::JsonObject' has no member named 'success'
     if (!root.success())
               ^
src/main.cpp: In function 'void saveConfiguration(const char*, const Configuration&)':
src/main.cpp:68:21: error: expected primary-expression before '<' token
     StaticJsonBuffer<384> jsonBuffer;
                     ^
src/main.cpp:68:27: error: 'jsonBuffer' was not declared in this scope
     StaticJsonBuffer<384> jsonBuffer;
                           ^
src/main.cpp:81:14: error: 'ArduinoJson::JsonObject' has no member named 'printTo'
     if (root.printTo(file) == 0)
              ^
src/main.cpp: In lambda function:
src/main.cpp:125:27: error: 'jsonBuffer' was not declared in this scope
         DynamicJsonBuffer jsonBuffer;
                           ^
src/main.cpp:153:14: error: 'ArduinoJson::JsonObject' has no member named 'printTo'
         root.printTo(response);
              ^
*** [.pio/build/esp12e/src/main.cpp.o] Error 1
================================================ [FAILED] Took 2.56 seconds ================================================
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
`

How can I upgrade to ArduinoJson 6 version?
Thanks.

**Comment by baptistecdr** [comment]
Hello,

I just pushed some code, it compiles but I can't test if it works, I don't have a PS4 Jailbreak anymore.

Best regards,
baptistecdr
